version: '2'
services:
    web:
        build:
            context: ./
            dockerfile: deploy/web.docker
        volumes:
            - ./:/var/www
        ports:
            - "8080:80"
            - "4431:443"
        links:
            - app
    app:
        build:
            context: ./
            dockerfile: deploy/app.docker
        volumes:
            - ./:/var/www
        links:
            - database
        #uncomment this for use Redis as cache#    - cache 
        environment:
            - "DB_PORT=3306"
            - "DB_HOST=database"
    database:
        image: mysql:5.6
        volumes:
            - ./storage/database/:/var/lib/mysql/
        environment:
            - "MYSQL_ROOT_PASSWORD=secret"
            - "MYSQL_DATABASE=dockerApp"
        ports:
            - "33061:3306"

##If Redis as cache is necessary uncomment the follow lines
    # cache:
    #     image: redis:3.0
    #     ports:
    #         - "63791:6379"